#!/bin/bash

set -u

# Please populate the following variables with details of your migration

# The name of the khulnasoft server image. Defaults to "khulnasoft/server"
IMAGE=

# The khulnasoft version running on both the source and destination hosts. NOTE: this version must be the same when migration data ie : 3.24.1
VERSION=

# The username and hostname of the host you will be migrating from. Takes the form of username@host ie: khulnasoft-user@myhost
SRC_HOST=

# The username and hostname of the host you will be migrating too. Takes the form of username@host ie: khulnasoft-user@myhost
DST_HOST=

# Fully qualified path to the docker-compose directory on a host
COMPOSE_DIR=
